/** Texts ported from StaticClasses/Operations.resx and Instructions.resx (pl-PL). */

export const MICRO_OP_DESCRIPTIONS: Readonly<Record<string, string>> = {
  ADD: 'ALU = LALU + RALU',
  ALA: 'arytmetyczne A w lewo',
  AND: 'ALU = LALU AND RALU',
  AQ15: 'NOT A0 -> MQ15',
  ARA: 'arytmetyczne A w prawo',
  CEA: 'Oblicz adres efektywny',
  CMA: 'ALU = (NOT LALU)+1',
  CMX: 'ALU = (NOT RALU)+1',
  CWC: 'Rozpoczęcie CWC',
  DECL: 'ALU = LALU - 1',
  DECR: 'ALU = RALU - 1',
  DIV: '15 -> LK',
  DLK: 'LK = [LK]-1',
  DRI: 'RI = RI-1',
  END: 'Koniec mikroprogramu',
  ENI: 'Odblokuj przerwania',
  EOR: 'ALU = LALU XOR RALU',
  IA: 'BUS -> A',
  IALU: 'A -> LALU',
  IAS: 'A0 -> ZNAK',
  IBE: 'BUS -> RALU',
  IBI: 'BUS -> RAE',
  ILK: 'BUS -> LK',
  ILR: 'BUS -> LR',
  IMQ: 'BUS -> MQ',
  INCL: 'ALU = LALU + 1',
  INCR: 'ALU = RALU + 1',
  IRAE: 'SUMA -> RAE',
  IRAP: 'BUS -> RAP',
  IRBP: 'BUS -> RBP',
  IRI: 'BUS -> RI',
  IRR: 'BUS -> RR',
  IWC: 'Rozpoczęcie IWC',
  IX: 'BUS -> X',
  IXRE: 'RI -> LALU',
  L: 'ALU = LALU',
  LCA: 'cykliczne A w lewo',
  LLA: 'logiczne A w lewo',
  LLQ: 'logiczne A i MQ w lewo',
  LRA: 'logiczne A w prawo',
  LRQ: 'logiczne A i MQ w prawo',
  MUL: '16 -> LK',
  NOTL: 'ALU = NOT LALU',
  NOTR: 'ALU = NOT RALU',
  NSI: 'LR+1 -> LR',
  OA: 'A -> BUS',
  OBE: 'ALU -> BUS',
  OLR: 'LR -> BUS',
  OMQ: 'MQ -> BUS',
  ONE: 'ALU = 1',
  OPC: 'OP albo AOP+32 -> RAPS',
  OR: 'ALU = LALU OR RALU',
  ORAE: 'RAE -> BUS',
  ORBP: 'RBP -> BUS',
  ORI: 'RI -> BUS',
  ORR: 'RR -> BUS',
  OX: 'X -> BUS',
  OXE: 'X -> RALU',
  R: 'ALU = RALU',
  RA: 'A = 0',
  RINT: 'INT = 0',
  RMQ: 'MQ = 0',
  ROFF: 'OFF = 0',
  RRC: 'Rozpoczęcie RRC',
  RXRO: 'XRO = 0',
  SGN: 'X0 -> ZNAK',
  SHT: 'Operacja przesunięcia',
  SOFF: 'OFF = 1',
  SRBP: 'BUS -> RBP',
  SUB: 'ALU = LALU - RALU',
  SXRO: 'XRO = 1',
  TAO: 'OFF = 0',
  TAP: 'A <= 0',
  TAS: 'A >= 0',
  TAZ: 'A = 0',
  TIND: 'Adresowanie pośrednie',
  TINT: 'Brak przerwania',
  TLK: 'SHT, LK=0 || !SHT, LK!=0',
  TQ15: 'MQ15 = 0',
  TSD: 'ZNAK = 0',
  TXP: 'RI <= 0',
  TXRO: 'XRO = 0',
  TXS: 'RI >= 0',
  TXZ: 'BXZ i RI != 0 || TLD i RI = 0',
  UNB: 'Zawsze pozytywny',
  ZERO: 'ALU = 0',
};

export const INSTRUCTION_DESCRIPTIONS: Readonly<Record<string, string>> = {
  ADD: 'Dodawanie',
  ADX: 'Dodaj do RI',
  ALA: 'Przesunięcie arytmetyczne A w lewo',
  ARA: 'Przesunięcie arytmetyczne A w prawo',
  BAN: 'Skocz jeśli A < 0',
  BAO: 'Skocz jeśli nadmiar A',
  BAP: 'Skocz jeśli A > 0',
  BAZ: 'Skocz jeśli A = 0',
  BDN: 'Skok jeśli urządzenie niedostępne',
  BXN: 'Skocz jeśli RI < 0',
  BXP: 'Skocz jeśli RI > 0',
  BXZ: 'Skocz jeśli RI = 0',
  CMA: 'Uzupełnienie A do 2',
  CND: 'Podłącz urządzenie',
  DEX: 'Zmniejsz modyfikator RI',
  DIV: 'Dzielenie',
  ENI: 'Zezwolenie na przerwania',
  EOR: 'Różnica symetryczna A i komórki',
  INX: 'Zwiększ modyfikator RI',
  LAI: 'Ładuj A bezpośrednio',
  LCA: 'Przesunięcie cykliczne A w lewo',
  LDA: 'Ładuj akumulator A',
  LDS: 'Podaj status',
  LDX: 'Ładuj modyfikator RI',
  LIO: 'Ładuj licznik słów WE-WY',
  LLA: 'Przesunięcie logiczne A w lewo',
  LLQ: 'Przesunięcie logiczne A || MQ w lewo',
  LNG: 'Negacja logiczna A',
  LOR: 'Suma logiczna A i komórki',
  LAND: 'Iloczyn logiczny A i komórki',
  LRA: 'Przesunięcie logiczne A w prawo',
  LRQ: 'Przesunięcie logiczne A || MQ w prawo',
  LXI: 'Ładuj RI bezpośrednio',
  MUL: 'Mnożenie',
  NOP: 'Nic nie rób',
  SIO: 'Start operacji WE-WY',
  SRJ: 'Skok ze śladem',
  STA: 'Zapamiętaj akumulator A',
  STC: 'Zapamiętaj LR',
  STP: 'Stop dynamiczny',
  STQ: 'Zapamiętaj rejestr MQ',
  STX: 'Zapamiętaj modyfikator RI',
  SUB: 'Odejmowanie',
  TLD: 'RI = RI - 1 i Skocz jeśli RI > 0',
  TMQ: 'Prześlij MQ do A',
  TXA: 'Prześlij RI do A',
  UNB: 'Skok bezwarunkowy',
};
